# similar to res.partner create model for hospital

import requests
import json
import logging
from odoo import api, fields, models
import logging

_logger = logging.getLogger(__name__)

class HospitalAppointment(models.Model):
    
    _name= 'hospital.appointment'
    #mail.therad class define in mail module of odoo, add dependncy of mail module in manifest.py
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _description= 'Hospital Appointment'
    _rec_name = 'patient_id'




# up till now this will create the table in the database

    #many2one field of patient_id
    #calling patient to record their appointment, this will create a dropdown of patient in appointment form
    reference= fields.Char(string="Reference", default='New')
    patient_id = fields.Many2one('hospital.patient', string="Patient", required=True, tracking=True, ondelete= 'cascade')


    date_appointment = fields.Datetime(string="Date", required=True, tracking=True)
    note = fields.Text(string="Note", tracking=True)


    ai_response = fields.Text(string="AI Recommendation", readonly=True)



    state = fields.Selection([('draft', 'Draft'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'),('done', 'Done'), ('cancel', 'Cancelled')], default='draft', tracking=True)


#inhering or overriding create method to generate sequence for reference field in appointment model, this will generate unique reference for each appointment record
    @api.model_create_multi
    #prints the values of the record being created, this is useful for debugging and understanding the flow of data in the create method
    def create(self, vals_list):
        #self contains current recordset, which is the appointment record being created, vals_list is a list of dictionaries containing the values for the new records being created, each dictionary corresponds to a record and contains the field names as keys and their corresponding values as values
        _logger.info("Creating hospital appointment with values: %s", vals_list)
        for vals in vals_list:
            #for the first time refeernce field will be empty or 'New', so we need to check if the reference field is empty or 'New' before generating a new sequence for it, this is to ensure that we only generate a new sequence for new records and not for existing records that are being updated
            if not vals.get('reference') or vals['reference'] == 'New':
                #if the reference field is 'New', it means that a new appointment record is being created and we need to generate a unique reference for it using the sequence defined in the data/sequence.xml file, the sequence is identified by the code 'hospital.appointment.sequence'

                #change reference field value to the next sequence value generated by the ir.sequence model, if the sequence generation fails for some reason, it will default to 'New'
                vals['reference'] = self.env['ir.sequence'].next_by_code('hospital.appointment') or 'New'
                #i need next sequence value of the code i set in sequence.xml file for the sequence , if the code is not found it will return 'New'
        return super().create(vals_list)
    

#this method will be called when the confirm button is clicked in the appointment form view, it will change the state of the appointment to 'confirmed'
    def action_confirm(self):
        #self represent current record opened in ui 
        for rec in self:
            rec.state = 'confirmed'
            
    def action_ongoing(self):
        #self represent current record opened in ui 
        for rec in self:
            rec.state = 'ongoing'
            
    def action_done(self):
        #self represent current record opened in ui 
        for rec in self:
            rec.state = 'done'
            
    def action_cancel(self):
        #self represent current record opened in ui 
        for rec in self:
            rec.state = 'cancel'


    def action_ask_ai(self):
        for rec in self:

            api_key= self.env['ir.config_parameter'].sudo().get_param('gemini_key')

            if not api_key:
                rec.ai_response = "API key not found. Please set the 'gemini_key' parameter in the system configuration."
                continue

            if not rec.note:
                rec.ai_response = "Please provide a note with symptoms or details for AI recommendation."
                continue

            url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"

            # 3️⃣ Create Prompt
            prompt = f"""
            Act as a professional doctor.

            Patient Symptoms:
            {rec.note}
            Provide a detailed recommendation for diagnosis and treatment based on the symptoms provided.
            """
            payload = {
                "contents":[
                    {
                        "parts":[
                            {
                                "text": prompt
                            }
                        ]
                    }
                ]
            }

            headers = {
                "Content-Type": "application/json" }
            
            try:
                #send json request to the API endpoint with a timeout of 30 seconds, if the API does not respond within this time frame, it will raise a timeout exception which we can catch and handle gracefully
                response = requests.post(url, headers=headers, json=payload, timeout=30)

                if response.status_code == 200:
                    result = response.json()

                    ai_text = result["candidates"][0]["content"]["parts"][0]["text"]

                    _logger.info("AI Response: %s", ai_text)   

                    rec.ai_response = ai_text

                else:
                    _logger.error("Gemini Error Status: %s", response.status_code)
                    _logger.error("Gemini Error Response: %s", response.text)

                    rec.ai_response = f"API Error {response.status_code}"

            except Exception as e:
                _logger.error("Connection Error: %s", str(e))
                rec.ai_response = f"Connection Error: {str(e)}"






       
            


 



